#ifndef TC_FILE_TYPES_H
#define TC_FILE_TYPES_H

typedef enum {
    FILE_TYPE_UNKNOWN = 0,
    FILE_TYPE_SYSTEM,
    FILE_TYPE_TEXT,
    FILE_TYPE_C,
    FILE_TYPE_CPP,
    FILE_TYPE_PYTHON,
    FILE_TYPE_JAVASCRIPT,
    FILE_TYPE_JAVA,
    FILE_TYPE_GO,
    FILE_TYPE_RUST,
    FILE_TYPE_HTML,
    FILE_TYPE_CSS,
    FILE_TYPE_JSON,
    FILE_TYPE_XML,
    FILE_TYPE_YAML,
    FILE_TYPE_CONFIG,
    FILE_TYPE_SCRIPT,
    FILE_TYPE_DOCUMENT,
    FILE_TYPE_IMAGE,
    FILE_TYPE_IMAGE_RAW,
    FILE_TYPE_IMAGE_VECTOR,
    FILE_TYPE_AUDIO,
    FILE_TYPE_AUDIO_PCM,
    FILE_TYPE_VIDEO,
    FILE_TYPE_ARCHIVE,
    FILE_TYPE_ARCHIVE_RAR,
    FILE_TYPE_ARCHIVE_7Z,
    FILE_TYPE_DATABASE,
    FILE_TYPE_SPREADSHEET,
    FILE_TYPE_PRESENTATION,
    FILE_TYPE_FONT,
    FILE_TYPE_BINARY,
    FILE_TYPE_TEMP,
    FILE_TYPE_VIRTUAL,
    FILE_TYPE_MARKDOWN,
    FILE_TYPE_AMBIGUOUS_RAW,
    FILE_TYPE_DIRECTORY,
    FILE_TYPE_COUNT
} FileType;

#define FILE_CATEGORY_TEXT      (1u << 0)
#define FILE_CATEGORY_PCM       (1u << 1)
#define FILE_CATEGORY_IMAGE     (1u << 2)
#define FILE_CATEGORY_SYSTEM    (1u << 3)
#define FILE_CATEGORY_RAW       (1u << 4)
#define FILE_CATEGORY_ARCHIVE   (1u << 5)
#define FILE_CATEGORY_AUDIO     (1u << 6)
#define FILE_CATEGORY_VIDEO     (1u << 7)

#endif
